/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package module2;

/**
 *
 * @author frank lou
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("3.14");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 60));

        btn2.setBackground(new java.awt.Color(255, 255, 255));
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/7.png"))); // NOI18N
        btn2.setContentAreaFilled(false);
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 90, 80));

        btn3.setBackground(new java.awt.Color(255, 255, 255));
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/8.png"))); // NOI18N
        btn3.setContentAreaFilled(false);
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 90, 80));

        btn4.setBackground(new java.awt.Color(255, 255, 255));
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/9.png"))); // NOI18N
        btn4.setContentAreaFilled(false);
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 90, 80));

        btn5.setBackground(new java.awt.Color(255, 255, 255));
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/6.png"))); // NOI18N
        btn5.setContentAreaFilled(false);
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 90, 80));

        btn6.setBackground(new java.awt.Color(255, 255, 255));
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/5.png"))); // NOI18N
        btn6.setContentAreaFilled(false);
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 90, 80));

        btn7.setBackground(new java.awt.Color(255, 255, 255));
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/4.png"))); // NOI18N
        btn7.setContentAreaFilled(false);
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 90, 80));

        btn8.setBackground(new java.awt.Color(255, 255, 255));
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/0.png"))); // NOI18N
        btn8.setContentAreaFilled(false);
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 180, 80));

        btn9.setBackground(new java.awt.Color(255, 255, 255));
        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/2.png"))); // NOI18N
        btn9.setContentAreaFilled(false);
        jPanel1.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 90, 80));

        btn10.setBackground(new java.awt.Color(255, 255, 255));
        btn10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/dot.png"))); // NOI18N
        btn10.setContentAreaFilled(false);
        jPanel1.add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 90, 80));

        btn11.setBackground(new java.awt.Color(255, 255, 255));
        btn11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/1.png"))); // NOI18N
        btn11.setContentAreaFilled(false);
        jPanel1.add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 90, 80));

        btn12.setBackground(new java.awt.Color(255, 255, 255));
        btn12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/3.png"))); // NOI18N
        btn12.setContentAreaFilled(false);
        jPanel1.add(btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 90, 80));

        btn13.setBackground(new java.awt.Color(255, 255, 255));
        btn13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/divide.png"))); // NOI18N
        btn13.setContentAreaFilled(false);
        jPanel1.add(btn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 90, 80));

        btn14.setBackground(new java.awt.Color(255, 255, 255));
        btn14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/times.png"))); // NOI18N
        btn14.setContentAreaFilled(false);
        jPanel1.add(btn14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 90, 80));

        btn15.setBackground(new java.awt.Color(255, 255, 255));
        btn15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/minus.png"))); // NOI18N
        btn15.setContentAreaFilled(false);
        jPanel1.add(btn15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 90, 80));

        btn16.setBackground(new java.awt.Color(255, 255, 255));
        btn16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/plus.png"))); // NOI18N
        btn16.setContentAreaFilled(false);
        jPanel1.add(btn16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 90, 80));

        btn17.setBackground(new java.awt.Color(255, 255, 255));
        btn17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/clear.png"))); // NOI18N
        btn17.setContentAreaFilled(false);
        jPanel1.add(btn17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 90, 80));

        btn18.setBackground(new java.awt.Color(255, 255, 255));
        btn18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/equals.png"))); // NOI18N
        btn18.setContentAreaFilled(false);
        jPanel1.add(btn18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 90, 80));

        btn19.setBackground(new java.awt.Color(255, 255, 255));
        btn19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/clear-all.png"))); // NOI18N
        btn19.setContentAreaFilled(false);
        btn19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn19MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn19MouseReleased(evt);
            }
        });
        jPanel1.add(btn19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 180, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn19MousePressed
         btn19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/clear-all-clicked.png")));
    }//GEN-LAST:event_btn19MousePressed

    private void btn19MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn19MouseReleased
       btn19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/clear-all.png")));
    }//GEN-LAST:event_btn19MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
